- name: configuring mysql server
  hosts: mysql
  become: yes     #root access
  tasks:
  - name: install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: installed
      