- name: configuring mysql server
  hosts: mysql
  become: yes     #root access
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
  - name: install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: enable and start mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes 

  - name: connect to sql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{mysql_root_password}}"
      login_host: mysql.shabbupractice.online
      register: mysql_info
      ignore_errors: true


